version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    command: mix phx.server
    environment:
      - MIX_ENV=dev
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
